version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2  # Versión de PHP que se utilizará

  build:
    commands:
      - echo "Evaluando la sintaxis del código PHP"
      - find . -name "*.php" -exec php -l {} \;  # Verificar la sintaxis de todos los archivos PHP

artifacts:
  files:
    - '**/*'
